# problem statement: enter 18(int) and 18(string ) elements
# in a set.
num = set()
n = input("Enter the number:")
num.add(int(n))
n = input("Enter the number:")
num.add(int(n))
n = input("Enter the number:")
num.add(int(n))
n = input("Enter the number:")
num.add(int(n))
n = input("Enter the number:")
num.add(int(n))
n = input("Enter the number:")
num.add(int(n))
n = input("Enter the number:")
num.add(int(n))
n = input("Enter the number:")
num.add(int(n))
n = input("Enter the number:")
num.add(int(n))
n = input("Enter the number:")
num.add(int(n))
n = input("Enter the number:")
num.add(int(n))
n = input("Enter the number:")
num.add(int(n))
n = input("Enter the number:")
num.add(int(n))
n = input("Enter the number:")
num.add(int(n))
n = input("Enter the number:")
num.add(int(n))
n = input("Enter the number:")
num.add(int(n))
n = input("Enter the number:")
num.add(int(n))
n = input("Enter the number:")
num.add(int(n))
n = input("Enter the number(string format):")
num.add(n)
n = input("Enter the number(string format):")
num.add(n)
n = input("Enter the number(string format):")
num.add(n)
n = input("Enter the number(string format):")
num.add(n)
n = input("Enter the number(string format):")
num.add(n)
n = input("Enter the number(string format):")
num.add(n)
n = input("Enter the number(string format):")
num.add(n)
n = input("Enter the number(string format):")
num.add(n)
n = input("Enter the number(string format):")
num.add(n)
n = input("Enter the number(string format):")
num.add(n)
n = input("Enter the number(string format):")
num.add(n)
n = input("Enter the number(string format):")
num.add(n)
n = input("Enter the number(string format):")
num.add(n)
n = input("Enter the number(string format):")
num.add(n)
n = input("Enter the number(string format):")
num.add(n)
n = input("Enter the number(string format):")
num.add(n)
n = input("Enter the number(string format):")
num.add(n)
n = input("Enter the number(string format):")
num.add(n)
print(num)